/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { NotesApp } from "./NotesApp";
export * as factories from "./factories";
export { NotesApp__factory } from "./factories/NotesApp__factory";
